### ISSUE TITLE
Invalid constant key

### ISSUE THREAD

**Issue by mateuszzaremba1** [segment-integrations/analytics-kotlin-consent#9]
**Describe the bug**

While testing the consent manager, I noticed that the `CATEGORY_PREFERENCE_KEY` has the value `categoryPreference` instead of `categoryPreferences`

**Platform (please complete the following information):**
 - Library Version in use: [1.2.3]
 - Platform being tested: [Android]

**Comment by jstarczewski** [comment]
The question is whether the key in the SDK is correct or not, as all the samples on Web (as well as in this repository the sample JSON in README.md) use the name `categoryPreferences`. We have troubles integrating consent management in our current project and we are wondering whether there is something odd on our side or the SDK has a typo in the key name. Let us know whether you need some examples :)

**Comment by jstarczewski** [comment]
Also sorry for the spamming, but pinging @didiergarcia and @alanjcharles as I see you were highly involved in the SDK development, maybe you can help us to confirm whether this is the issue or not :)

**Comment by mateuszzaremba1** [comment]
@didiergarcia  @alanjcharles @bsneed Any update ?

**Comment by didiergarcia** [comment]
@mateuszzaremba1 thanks for let us know. We're going to fix this soon.

**Comment by didiergarcia** [comment]
Hi @mateuszzaremba1 This has been corrected in the latest release.

Please note that we also updated the published group name so the dependency should be:

implementation("com.segment.analytics.kotlin:consent:1.5.2")
